# Generated by Django 3.1.4 on 2020-12-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201215_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
